# Data path. adjust them!
common:
#    image_file: "/home/mcqueen-zero/WorkProjects/MFO_SLAM/datasets/My_Self/hat/calibration/image/0.png"
#    pcd_file: "/home/mcqueen-zero/WorkProjects/MFO_SLAM/datasets/My_Self/hat/calibration/pcd/0.pcd"
#    result_file: "/home/mcqueen-zero/WorkProjects/MFO_SLAM/datasets/My_Self/hat/calibration/extrinsic.txt"
#    image_file: "/home/mcqueen-zero/WorkProjects/MFO_SLAM/datasets/My_Self/handheld/calibration/indoor/image/0.png"
#    pcd_file: "/home/mcqueen-zero/WorkProjects/MFO_SLAM/datasets/My_Self/handheld/calibration/indoor/pcd/0.pcd"
#    result_file: "/home/mcqueen-zero/WorkProjects/MFO_SLAM/datasets/My_Self/handheld/calibration/indoor/extrinsic.txt"
    image_file: "/home/mcqueen-zero/WorkProjects/MFO_SLAM/datasets/My_Self/handheld/calibration/outdoor/image/0.png"
    pcd_file: "/home/mcqueen-zero/WorkProjects/MFO_SLAM/datasets/My_Self/handheld/calibration/outdoor/pcd/0.pcd"
    result_file: "/home/mcqueen-zero/WorkProjects/MFO_SLAM/datasets/My_Self/handheld/calibration/outdoor/extrinsic.txt"

# Camera Parameters. Adjust them!
camera:
# Rough
#    camera_matrix: [641.6396, 0.0, 640.1515,
#                    0.0,  641.0463, 401.3607,
#                    0.0, 0.0, 1.0 ]
#    dist_coeffs: [-0.0563693, 0.0636890, -6.43375e-04, 1.37395e-04, -0.0203666]
# Fine
    camera_matrix: [651.1561, 0.0, 636.8555,
                    0.0,  651.5606, 401.2339,
                    0.0, 0.0, 1.0 ]
    dist_coeffs: [-0.0482273, 0.0906810, -0.00231148, -0.00152441, 0.000000]

# Calibration Parameters.!
calib:
#    calib_config_file: "/home/mcqueen-zero/WorkProjects/MFO_SLAM/src/livox_camera_calib/config/config_hat.yaml"
#    calib_config_file: "/home/mcqueen-zero/WorkProjects/MFO_SLAM/src/livox_camera_calib/config/config_indoor.yaml"
    calib_config_file: "/home/mcqueen-zero/WorkProjects/MFO_SLAM/src/livox_camera_calib/config/config_outdoor.yaml"
    use_rough_calib: true # set true if your initial_extrinsic is bad
