# Data path. adjust them!
common:
    image_file: "/home/mcqueen-zero/WorkProjects/MFO_SLAM/datasets/calibration/outdoor/image/0.png"
    pcd_file: "/home/mcqueen-zero/WorkProjects/MFO_SLAM/datasets/calibration/outdoor/pcd/0.pcd"
    result_file: "/home/mcqueen-zero/WorkProjects/MFO_SLAM/datasets/calibration/outdoor/extrinsic.txt"

# Camera Parameters. Adjust them!
camera:
    camera_matrix: [641.6396, 0.0, 640.1515,
                    0.0,  641.0463, 401.3607,
                    0.0, 0.0, 1.0 ]
    dist_coeffs: [-0.0563693, 0.0636890, -6.43375e-04, 1.37395e-04, -0.0203666]

# Calibration Parameters.!
calib:
    calib_config_file: "/home/mcqueen-zero/WorkProjects/MFO_SLAM/src/livox_camera_calib/config/config_outdoor.yaml"
    use_rough_calib: true # set true if your initial_extrinsic is bad
